/opt/conda/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "gpu5.py", line 7, in <module>
    trainset = CIFAR10(root='./data', train=True, download=True, transform=transform)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 60, in __init__
    super().__init__(root, transform=transform, target_transform=target_transform)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/vision.py", line 39, in __init__
    if isinstance(root, torch._six.string_classes):
AttributeError: module 'torch' has no attribute '_six'
